name: GS1-Trustbox
channels:
  - defaults
dependencies:
  - numpy=1.18.1
  - pandas=1.0.3
  - scikit-learn=0.22.1
  - xlrd=1.2.0
  - nltk=3.4.5
  - pip:
      - mlflow
      - google-cloud-storage
      - pandarallel==1.4.8
